name: MyCI

on:
    push:
        branches:
            - main

jobs:
    hello:
        name: My first job
        runs-on: ubuntu-latest
        steps:
            - name: My first step
              run: echo "Hello world"

    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps: 
            - name: Install package
              run: pip install .[test]
            - name: Run pytest
              run: python -m pytest -v
